
import { User, Skill, Match, Session, Feedback, Notification, Task, Badge, Report, Post } from './types';

export const BADGES: Badge[] = [
    { id: 'b1', name: 'Early Adopter', description: 'Joined SkillHive during the beta phase.', icon: '🚀', color: 'blue', category: 'trust' },
    { id: 'b2', name: 'Task Master', description: 'Completed 5 learning tasks.', icon: '⚡', color: 'yellow', category: 'achievement' },
    { id: 'b3', name: 'Reliable Peer', description: 'Completed 3 exchange sessions successfully.', icon: '🤝', color: 'green', category: 'trust' },
    { id: 'b4', name: 'Top Mentor', description: 'Received a 5-star rating from a peer.', icon: '⭐', color: 'purple', category: 'appreciation' },
    { id: 'b5', name: 'Knowledge Seeker', description: 'Created 5 new tasks to learn skills.', icon: '📚', color: 'orange', category: 'achievement' },
    { id: 'b6', name: 'Verified Identity', description: 'User identity has been verified.', icon: '🛡️', color: 'teal', category: 'trust' },
];

export const SKILLS: Skill[] = [
  { id: 's1', name: 'Project Management', category: 'Business', description: 'Learn to manage projects effectively using Agile methodologies.', ownerId: '1', tags: ['agile', 'scrum', 'leadership'], level: 'Expert' },
  { id: 's2', name: 'React Development', category: 'Technology', description: 'Master the fundamentals of React, including hooks and architecture.', ownerId: '2', tags: ['frontend', 'javascript', 'webdev'], level: 'Advanced' },
  { id: 's3', name: 'Creative Writing', category: 'Arts', description: 'Unlock your storytelling potential and learn techniques for fiction.', ownerId: '3', tags: ['writing', 'storytelling', 'fiction'], level: 'Intermediate' },
  { id: 's4', name: 'Node.js Backend', category: 'Technology', description: 'Build scalable and efficient server-side applications.', ownerId: '4', tags: ['backend', 'api', 'javascript'], level: 'Intermediate' },
  { id: 's5', name: 'UI/UX Design', category: 'Design', description: 'Principles of user-centric design, wireframing, and prototyping.', ownerId: '5', tags: ['design', 'figma', 'ux'], level: 'Advanced' },
  { id: 's6', name: 'Data Science', category: 'Technology', description: 'Introduction to data analysis and visualization using Python.', ownerId: '6', tags: ['python', 'data', 'analysis'], level: 'Intermediate' },
  { id: 's7', name: 'Digital Photography', category: 'Arts', description: 'Master manual settings and composition for stunning photos.', ownerId: '7', tags: ['photo', 'editing', 'camera'], level: 'Expert' },
  { id: 's8', name: 'Personal Finance', category: 'Business', description: 'Budgeting, investing basics, and long-term financial planning.', ownerId: '8', tags: ['money', 'investing', 'budget'], level: 'Advanced' },
  { id: 's9', name: 'Acoustic Guitar', category: 'Music', description: 'Learn chords, strumming patterns, and your favorite songs.', ownerId: '9', tags: ['music', 'guitar', 'instrument'], level: 'Intermediate' },
  { id: 's10', name: 'Spanish Language', category: 'Language', description: 'Conversational Spanish for travelers and enthusiasts.', ownerId: '10', tags: ['spanish', 'language', 'culture'], level: 'Advanced' },
  { id: 's11', name: 'Yoga & Mindfulness', category: 'Lifestyle', description: 'Improve flexibility and mental clarity through daily practice.', ownerId: '11', tags: ['wellness', 'yoga', 'health'], level: 'Expert' },
  { id: 's12', name: 'Video Editing', category: 'Technology', description: 'Edit high-quality videos using Premiere Pro and DaVinci.', ownerId: '12', tags: ['video', 'editing', 'youtube'], level: 'Advanced' },
  // FIX: Added missing quotes around description for skill s13
  { id: 's13', name: 'Public Speaking', category: 'Business', description: 'Confidently deliver speeches and presentations to any audience.', ownerId: '13', tags: ['speech', 'confidence', 'career'], level: 'Intermediate' },
  { id: 's14', name: 'Digital Marketing', category: 'Business', description: 'Master SEO, SEM, and social media growth strategies.', ownerId: '14', tags: ['marketing', 'seo', 'growth'], level: 'Advanced' },
  { id: 's15', name: 'Italian Cooking', category: 'Lifestyle', description: 'Learn to make authentic pasta and sauces from scratch.', ownerId: '15', tags: ['food', 'cooking', 'italy'], level: 'Intermediate' },
  { id: 's16', name: 'Chess Strategy', category: 'Lifestyle', description: 'Advanced opening theory and endgame tactics.', ownerId: '16', tags: ['chess', 'game', 'logic'], level: 'Expert' },
  { id: 's17', name: 'Graphic Design', category: 'Design', description: 'Create brand identities and layouts using Illustrator.', ownerId: '17', tags: ['design', 'branding', 'vector'], level: 'Advanced' },
  { id: 's18', name: 'Piano Basics', category: 'Music', description: 'Learn to read music and play classic piano pieces.', ownerId: '18', tags: ['music', 'piano', 'classical'], level: 'Beginner' },
  { id: 's19', name: 'French Language', category: 'Language', description: 'Intermediate French focusing on grammar and fluid speech.', ownerId: '19', tags: ['french', 'language', 'paris'], level: 'Intermediate' },
  { id: 's20', name: 'Organic Gardening', category: 'Lifestyle', description: 'Grow your own vegetables and herbs without chemicals.', ownerId: '20', tags: ['garden', 'nature', 'food'], level: 'Beginner' },
  { id: 's21', name: 'Cybersecurity 101', category: 'Technology', description: 'Protect your digital life and understand basic networking.', ownerId: '4', tags: ['security', 'tech', 'privacy'], level: 'Advanced' },
  { id: 's22', name: 'Baking Desserts', category: 'Lifestyle', description: 'Advanced pastry techniques and cake decorating.', ownerId: '15', tags: ['baking', 'dessert', 'food'], level: 'Advanced' },
  { id: 's23', name: 'App Development', category: 'Technology', description: 'Create cross-platform mobile apps with Flutter.', ownerId: '2', tags: ['mobile', 'flutter', 'coding'], level: 'Intermediate' },
  { id: 's24', name: 'SQL Foundations', category: 'Technology', description: 'Relational database design and query optimization.', ownerId: '6', tags: ['sql', 'database', 'backend'], level: 'Advanced' },
  { id: 's25', name: 'Watercolor Painting', category: 'Arts', description: 'Techniques for light and shadow in landscape painting.', ownerId: '7', tags: ['art', 'painting', 'watercolor'], level: 'Intermediate' },
];

export const USERS: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@skillx.com',
    password: 'password123',
    bio: 'Platform Administrator. I help keep the community safe.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    skillsOffered: ['s1'],
    skillsWanted: ['s3', 's8'],
    verifiedSkills: ['s1'],
    availability: 'Mon-Fri 9am-5pm',
    rating: 4.9,
    role: 'admin',
    blockedUsers: [],
    credits: 1500,
    badges: ['b1', 'b6', 'b4']
  },
  {
    id: '2',
    name: 'Alice Johnson',
    email: 'alice@skillx.com',
    password: 'password123',
    bio: 'Frontend developer and Flutter enthusiast. Recently obsessed with high-performance React.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    skillsOffered: ['s2', 's23'],
    skillsWanted: ['s4', 's12'],
    availability: 'Weekends',
    rating: 4.8,
    role: 'user',
    blockedUsers: [],
    credits: 450,
    badges: ['b1', 'b2', 'b6']
  },
  {
    id: '3',
    name: 'Bob Williams',
    email: 'bob@skillx.com',
    password: 'password123',
    bio: 'Passionate storyteller and freelance copywriter.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    skillsOffered: ['s3'],
    skillsWanted: ['s2', 's10'],
    availability: 'Tue & Thu evenings',
    rating: 4.7,
    role: 'user',
    blockedUsers: [],
    credits: 280,
    badges: ['b3']
  },
  {
    id: '4',
    name: 'Charlie Brown',
    email: 'charlie@skillx.com',
    password: 'password123',
    bio: 'Security researcher and backend wizard. Looking for leadership skills.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie',
    skillsOffered: ['s4', 's21'],
    skillsWanted: ['s1', 's16'],
    availability: 'Mon & Wed evenings',
    rating: 4.9,
    role: 'user',
    blockedUsers: [],
    credits: 620,
    badges: ['b1', 'b6']
  },
  {
    id: '5',
    name: 'Diana Prince',
    email: 'diana@skillx.com',
    password: 'password123',
    bio: 'Product designer focusing on accessible experiences.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diana',
    skillsOffered: ['s5'],
    skillsWanted: ['s2', 's6'],
    availability: 'Flexible',
    rating: 5.0,
    role: 'user',
    blockedUsers: [],
    credits: 120,
    badges: ['b4']
  },
  {
    id: '6',
    name: 'Ethan Hunt',
    email: 'ethan@skillx.com',
    password: 'password123',
    bio: 'Data scientist who loves solving complex puzzles.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan',
    skillsOffered: ['s6', 's24'],
    skillsWanted: ['s11', 's21'],
    availability: 'Early mornings',
    rating: 4.6,
    role: 'user',
    blockedUsers: [],
    credits: 340,
    badges: ['b2']
  },
  {
    id: '7',
    name: 'Fiona Gallagher',
    email: 'fiona@skillx.com',
    password: 'password123',
    bio: 'Travel photographer and watercolor artist.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fiona',
    skillsOffered: ['s7', 's25'],
    skillsWanted: ['s15', 's19'],
    availability: 'Friday afternoons',
    rating: 4.9,
    role: 'user',
    blockedUsers: [],
    credits: 890,
    badges: ['b4', 'b6']
  },
  {
    id: '8',
    name: 'George Costanza',
    email: 'george@skillx.com',
    password: 'password123',
    bio: 'New here. I work in real estate but want to learn wellness.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=George',
    skillsOffered: ['s8'],
    skillsWanted: ['s11', 's13'],
    availability: 'Evenings only',
    rating: 4.2,
    role: 'user',
    blockedUsers: [],
    credits: 50,
    badges: ['b1']
  },
  {
    id: '9',
    name: 'Hannah Abbott',
    email: 'hannah@skillx.com',
    password: 'password123',
    bio: 'Guitarist and songwriter. Music is life!',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hannah',
    skillsOffered: ['s9'],
    skillsWanted: ['s17', 's5'],
    availability: 'Weekends',
    rating: 4.8,
    role: 'user',
    blockedUsers: [],
    credits: 210,
    badges: ['b3']
  },
  {
    id: '10',
    name: 'Ian Somer',
    email: 'ian@skillx.com',
    password: 'password123',
    bio: 'Bilingual traveler teaching Spanish.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ian',
    skillsOffered: ['s10'],
    skillsWanted: ['s12', 's14'],
    availability: 'Variable schedule',
    rating: 4.7,
    role: 'user',
    blockedUsers: [],
    credits: 175,
    badges: ['b1']
  },
  {
    id: '11',
    name: 'Julia Roberts',
    email: 'julia@skillx.com',
    password: 'password123',
    bio: 'Yoga instructor and meditation guide.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Julia',
    skillsOffered: ['s11'],
    skillsWanted: ['s15', 's20'],
    availability: 'Weekdays 7am-10am',
    rating: 5.0,
    role: 'user',
    blockedUsers: [],
    credits: 920,
    badges: ['b4', 'b3', 'b6']
  },
  {
    id: '12',
    name: 'Kevin Hart',
    email: 'kevin@skillx.com',
    password: 'password123',
    bio: 'High-energy video editor and comedian.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
    skillsOffered: ['s12'],
    skillsWanted: ['s13', 's1'],
    availability: 'Late nights',
    rating: 4.5,
    role: 'user',
    blockedUsers: [],
    credits: 410,
    badges: ['b2']
  },
  {
    id: '13',
    name: 'Laura Palmer',
    email: 'laura@skillx.com',
    password: 'password123',
    bio: 'Corporate trainer specializing in communication.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
    skillsOffered: ['s13'],
    skillsWanted: ['s19', 's3'],
    availability: 'Mon-Thu 5pm-8pm',
    rating: 4.8,
    role: 'user',
    blockedUsers: [],
    credits: 330,
    badges: ['b3']
  },
  {
    id: '14',
    name: 'Mike Wazowski',
    email: 'mike@skillx.com',
    password: 'password123',
    bio: 'Marketing expert and professional scaring consultant.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    skillsOffered: ['s14'],
    skillsWanted: ['s17', 's5'],
    availability: 'Always available',
    rating: 4.7,
    role: 'user',
    blockedUsers: [],
    credits: 560,
    badges: ['b2', 'b5']
  },
  {
    id: '15',
    name: 'Nina Ricci',
    email: 'nina@skillx.com',
    password: 'password123',
    bio: 'Executive chef and pastry lover.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
    skillsOffered: ['s15', 's22'],
    skillsWanted: ['s10', 's8'],
    availability: 'Sundays',
    rating: 4.9,
    role: 'user',
    blockedUsers: [],
    credits: 780,
    badges: ['b4', 'b6']
  },
  {
    id: '16',
    name: 'Oscar Wilde',
    email: 'oscar@skillx.com',
    password: 'password123',
    bio: 'Chess master and aesthetic philosopher.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oscar',
    skillsOffered: ['s16'],
    skillsWanted: ['s13', 's10'],
    availability: 'Wednesday nights',
    rating: 4.6,
    role: 'user',
    blockedUsers: [],
    credits: 240,
    badges: ['b1']
  },
  {
    id: '17',
    name: 'Paula Sher',
    email: 'paula@skillx.com',
    password: 'password123',
    bio: 'Legendary graphic designer and typographer. I mentor many students.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Paula',
    skillsOffered: ['s17'],
    skillsWanted: ['s23', 's2'],
    availability: 'Flexible',
    rating: 5.0,
    role: 'user',
    blockedUsers: [],
    credits: 1100,
    badges: ['b4', 'b6', 'b1']
  },
  {
    id: '18',
    name: 'Quentin Blake',
    email: 'quentin@skillx.com',
    password: 'password123',
    bio: 'Illustrator learning the keys to classical music.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Quentin',
    skillsOffered: ['s18'],
    skillsWanted: ['s7', 's25'],
    availability: 'Tue/Fri mornings',
    rating: 4.4,
    role: 'user',
    blockedUsers: [],
    credits: 90,
    badges: ['b1']
  },
  {
    id: '19',
    name: 'Rachel Green',
    email: 'rachel@skillx.com',
    password: 'password123',
    bio: 'French enthusiast and fashion consultant.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel',
    skillsOffered: ['s19'],
    skillsWanted: ['s15', 's22'],
    availability: 'Saturday mornings',
    rating: 4.7,
    role: 'user',
    blockedUsers: [],
    credits: 310,
    badges: ['b3']
  },
  {
    id: '20',
    name: 'Sam Wise',
    email: 'sam@skillx.com',
    password: 'password123',
    bio: 'Home gardener and nature lover.',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sam',
    skillsOffered: ['s20'],
    skillsWanted: ['s9', 's10'],
    availability: 'Mornings',
    rating: 4.8,
    role: 'user',
    blockedUsers: [],
    credits: 150,
    badges: ['b1']
  }
];

export const MATCHES: Match[] = [
  { id: 'm1', user1Id: '2', user2Id: '4', skillOfferedId: 's2', skillWantedId: 's4', status: 'accepted', scheduledTime: new Date('2024-11-15T14:00:00Z').toISOString(), meetLink: 'https://meet.google.com/mock-link-123' },
  { id: 'm2', user1Id: '1', user2Id: '3', skillOfferedId: 's1', skillWantedId: 's3', status: 'pending', scheduledTime: null, meetLink: null },
  { id: 'm3', user1Id: '7', user2Id: '15', skillOfferedId: 's7', skillWantedId: 's15', status: 'accepted', scheduledTime: null, meetLink: null },
];

export const SESSIONS: Session[] = [
  { id: 'ses1', matchId: 'm1', startTime: new Date('2024-11-01T14:00:00Z').toISOString(), endTime: new Date('2024-11-01T15:00:00Z').toISOString(), status: 'completed' },
];

export const FEEDBACKS: Feedback[] = [
  { id: 'f1', sessionId: 'ses1', fromUserId: '4', toUserId: '2', rating: 5, comment: 'Alice is a fantastic teacher! Her explanation of React hooks was incredibly clear.', createdAt: new Date('2024-11-01T15:05:00Z').toISOString() },
];

export const NOTIFICATIONS: Notification[] = [
    { id: 'n1', userId: '1', message: "Welcome to SkillHive! Start exploring skills to learn.", type: 'system', read: false, createdAt: new Date().toISOString() },
];

export const TASKS: Task[] = [
    { id: 't1', userId: '2', title: 'Complete React Tutorial', description: 'Finish the official React documentation tutorial.', difficulty: 'Medium', creditsReward: 25, status: 'pending', createdAt: new Date().toISOString() },
    { id: 't2', userId: '2', title: 'Build a Todo App', description: 'Create a simple Todo app using React hooks.', difficulty: 'Easy', creditsReward: 10, status: 'completed', createdAt: new Date().toISOString(), completedAt: new Date().toISOString() },
    { id: 't3', userId: '2', title: 'Master Framer Motion', description: 'Mastering advanced animations for UI.', difficulty: 'Hard', creditsReward: 50, status: 'completed', createdAt: new Date().toISOString(), completedAt: new Date().toISOString() },
];

export const REPORTS: Report[] = [
    { id: 'r1', reporterId: '2', reportedId: '3', reason: 'Spam', description: 'User sent repetitive messages.', status: 'pending', timestamp: new Date().toISOString() },
];

export const POSTS: Post[] = [
    {
        id: 'p1',
        userId: '2',
        title: 'Best resources for learning React?',
        content: 'I am looking for some advanced resources to master React performance optimization. Any suggestions?',
        tags: ['React', 'Frontend', 'Optimization'],
        likes: ['3', '4', '7'],
        type: 'question',
        comments: [
            { id: 'c1', userId: '4', text: 'I highly recommend "Advanced React Patterns" course.', createdAt: new Date(Date.now() - 86400000).toISOString() }
        ],
        createdAt: new Date(Date.now() - 172800000).toISOString()
    },
    {
        id: 'p2',
        userId: '11',
        title: 'Morning Yoga Tip',
        content: 'Just 5 minutes of sun salutations can change your entire energy level for the day!',
        tags: ['Yoga', 'Wellness', 'Morning'],
        likes: ['1', '2', '4', '5', '8'],
        type: 'tip',
        comments: [],
        createdAt: new Date(Date.now() - 43200000).toISOString()
    }
];